api:
    resource: "@AppBundle/Controller/Api/"
    type: annotation
    prefix: /api/v1

app:
    resource: "@AppBundle/Controller/Web/"
    type:     annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc