# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        chain_providers:
            chain:
                providers: [in_memory, my_db_provider]
        in_memory:
            memory:
                users:
                    diar:
                        password: diar123
                        roles: 'ROLE_USER'
        my_db_provider:
            entity:
                class: AppBundle:User
                property: email
    encoders:
        AppBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_USER: [ROLE_STORE, ROLE_USER, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            guard:
                authenticators:
                    - app.security.authenticator_guard
            logout:
                path: /logout
            switch_user: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/book*, roles: ROLE_USER }